export const FETCH_DATA_POKE = 'FETCH_DATA_POKE';
export const FETCH_DATA_POKE_SUCCESS = 'FETCH_DATA_POKE_SUCCESS';

export const FETCH_DATA_POKE_DETAIL = 'FETCH_DATA_POKE_DETAIL';
export const FETCH_DATA_POKE_DETAIL_SUCCESS = 'FETCH_DATA_POKE_DETAIL_SUCCESS';

// ROUTER
export const CHANGE_ROUTE = 'CHANGE_ROUTE';